author = "LitoMore"
base_url = "https://litomore.me"
compile_sass = true
description = "LitoMore's Mind"
default_language = 'en'
generate_feeds = true
minify_html = true
theme = "hacker"
title = "litomore.me"
taxonomies = [{ name = "tags" }]

[languages.zh]
title = "litomore.me"
description = "守望梦境"
generate_feeds = true
taxonomies = [{ name = "tags" }]

[markdown]
bottom_footnotes = true
external_links_no_follow = true
external_links_no_referrer = true
external_links_target_blank = true
highlight_code = true
highlight_theme = "charcoal"
render_emoji = true

[extra]
edit_page = false
language_code = "en-US"
logo = "favicon.svg"
monitor = false
opengraph = true
opengraph_images = ["og.webp"]
simplified_tags = false
timezone = "Asia/Singapore"
title_separator = "|"
menu = [
  { url = "about", name = "About" },
  { url = "friends", name = "Friends" },
  { url = "tags", name = "Tags", zh = true },
]
social_links = [
  { brand = 'listenhub', url = 'https://listenhub.ai/?utm_source=litomore.me&utm_medium=content&utm_content=footer', color = '/EAEAEA', shadow = '#EAEAEA', size = '16' },
  { icon = "rss", url = "https://litomore.me/atom.xml", shadow = "#FFA500", size = "19" },
  { icon = "github", url = "https://github.com/LitoMore", color = "/EAEAEA", shadow = "#EAEAEA" },
  { icon = "x", url = "https://x.com/LitoMore", color = "/EAEAEA", shadow = "#EAEAEA", size = "18" },
  { icon = "mastodon", url = "https://mastodon.social/@LitoMore", shadow = "#6364FF" },
  { icon = "bluesky", url = "https://bsky.app/profile/litomore.me", shadow = "#0285FF", size = "19" },
  { icon = "instagram", url = "https://instgram.com/instomore", shadow = "#E4405F" },
  { icon = "raycast", url = "https://raycast.com/litomore", shadow = "#FF6363" },
  { icon = "figma", url = "https://www.figma.com/@litomore", shadow = "#F24E1E" },
  { icon = "miro", url = "https://miro.com/marketplace/profile/109351/", color = "/FFDD33", shadow = "#FFDD33", size = "18" },
  { icon = "producthunt", url = "https://www.producthunt.com/@LitoMore", shadow = "#DA552F" },
  { icon = "spotify", url = "https://open.spotify.com/user/wz0506hvtyfkb0cx55ve9nogv", shadow = "#1DB954" },
  { icon = 'bilibili', url = 'http://live.bilibili.com/21532777', color = '/00A1D6', shadow = '#00A1D6', size = '18' },
  { icon = 'twitch', url = 'https://twitch.tv/LitoMore', color = '/9146FF', shadow = '#9146FF' },
  { icon = 'clubhouse', url = 'https://clubhouse.com/@litomore', color = '/FFE450', shadow = '#FFE450', size = '18' },
  { brand = 'linkedin', url = 'https://linkedin.com/in/litomore', color = '/0A66C2', shadow = '#0A66C2' },
  { icon = 'standardresume', url = 'https://rsm.io/litomore', color = '/2A3FFB', shadow = '#2A3FFB' },
  { icon = 'steam', url = 'https://steamcommunity.com/profile/LitoMore', color = '/EAEAEA', shadow = '#EAEAEA' },
  { icon = 'playstation', url = 'https://profile.playstation.com/PlaystaMore', color = '/0070D1', shadow = '#0070D1', size = '19' },
  { brand = 'nintendoswitch', url = 'https://lounge.nintendo.com/friendcode/0957-9664-7192/DShQJ14PtB', color = '/E60012', shadow = '#E60012' },
]

[extra.github]
repo = "litomore.me"
username = "LitoMore"
